//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FiveStarDemo.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FiveStarApplicantInterviewInformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FiveStarApplicantInterviewInformation()
        {
            this.FiveStarResidentInformation = new HashSet<FiveStarResidentInformation>();
        }

        public List<AllMentalHealthProfiles> AllMentalHealthProfiles { get; set; }

        public string AppIntInfo_FullName
        {
            get { return AppIntInfo_Fname + " " + AppIntInfo_Lname; }
        }
        public int AppIntInfo_ID { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public System.DateTime AppIntInfo_Date { get; set; }
        public string AppIntInfo_Status { get; set; }
        [Required(ErrorMessage = "You must provide a SSN")]
        [RegularExpression(@"^\d{9}|\d{3}-\d{2}-\d{4}$", ErrorMessage = "Invalid Social Security Number")]
        public string AppIntInfo_SSN { get; set; }
        [Required(ErrorMessage = "You must provide a First Name")]
        public string AppIntInfo_Fname { get; set; }
        [Required(ErrorMessage = "You must provide a Last Name")]
        public string AppIntInfo_Lname { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public System.DateTime AppIntInfo_DOB { get; set; }
        public Nullable<int> AppIntInfo_Age { get; set; }
        public Nullable<bool> AppIntInfo_MHCurrentHarm { get; set; }
        public Nullable<bool> AppIntInfo_MHPastHarm { get; set; }
        public string AppIntInfo_MHPastHarm_Details { get; set; }
        public Nullable<bool> AppIntInfo_MHTBI { get; set; }
        public Nullable<bool> AppIntInfo_MHPTS { get; set; }
        public Nullable<bool> AppIntInfo_MHSubAbuse { get; set; }
        public Nullable<bool> AppIntInfo_MHBipoDisorder { get; set; }
        public Nullable<bool> AppIntInfo_MHSchizo { get; set; }
        public Nullable<bool> AppIntInfo_MHDepression { get; set; }
        public Nullable<bool> AppIntInfo_MHAnxiety { get; set; }
        public Nullable<bool> AppIntInfo_MHPersDisorder { get; set; }
        public string AppIntInfo_MHOther { get; set; }
        public Nullable<bool> AppIntInfo_ASAAlcohol { get; set; }
        public Nullable<bool> AppIntInfo_ASAGambling { get; set; }
        public Nullable<bool> AppIntInfo_ASAPrescriptDrug { get; set; }
        public Nullable<bool> AppIntInfo_ASAStreetDrug { get; set; }
        public Nullable<bool> AppIntInfo_ASATobacco { get; set; }
        public string AppIntInfo_ASADrugChoice1 { get; set; }
        public string AppIntInfo_ASADrugChoice2 { get; set; }
        public string AppIntInfo_ASADrugChoice3 { get; set; }
        public string AppIntInfo_ASACurrent_TimeSober { get; set; }
        public string AppIntInfo_ASAPast_TimeSober { get; set; }
        public Nullable<bool> AppIntInfo_ASADUI_DWI { get; set; }
        public Nullable<bool> AppIntInfo_ASAPossess_Conviction { get; set; }
        public Nullable<bool> AppIntInfo_ASASell_Conviction { get; set; }
        public string AppIntInfo_PHPCP_Fname { get; set; }
        public string AppIntInfo_PHPCP_Lname { get; set; }
        public string AppIntInfo_PHPCP_Phone { get; set; }
        public string AppIntInfo_PHPCP_StAddress { get; set; }
        public string AppIntInfo_PHPCP_City { get; set; }
        public string AppIntInfo_PHPCP_State { get; set; }
        public string AppIntInfo_PHPCP_Zip { get; set; }
        public Nullable<bool> AppIntInfo_PHPCP_ContactOK { get; set; }
        public Nullable<bool> AppIntInfo_PHSeizures { get; set; }
        public string AppIntInfo_PHAllergies { get; set; }
        public string AppIntInfo_PHOther { get; set; }
        public string AppIntInfo_MedsCondition1 { get; set; }
        public string AppIntInfo_MedsMedication1 { get; set; }
        public string AppIntInfo_MedsDosage1 { get; set; }
        public string AppIntInfo_MedsFrequency1 { get; set; }
        public string AppIntInfo_MedsCondition2 { get; set; }
        public string AppIntInfo_MedsMedication2 { get; set; }
        public string AppIntInfo_MedsDosage2 { get; set; }
        public string AppIntInfo_MedsFrequency2 { get; set; }
        public string AppIntInfo_MedsCondition3 { get; set; }
        public string AppIntInfo_MedsMedication3 { get; set; }
        public string AppIntInfo_MedsDosage3 { get; set; }
        public string AppIntInfo_MedsFrequency3 { get; set; }
        public string AppIntInfo_MedsCondition4 { get; set; }
        public string AppIntInfo_MedsMedication4 { get; set; }
        public string AppIntInfo_MedsDosage4 { get; set; }
        public string AppIntInfo_MedsFrequency4 { get; set; }
        public string AppIntInfo_MedsCondition5 { get; set; }
        public string AppIntInfo_MedsMedication5 { get; set; }
        public string AppIntInfo_MedsDosage5 { get; set; }
        public string AppIntInfo_MedsFrequency5 { get; set; }
        public string AppIntInfo_MedsOther { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:d}")]
        public Nullable<System.DateTime> AppIntInfo_AgreeSignDate { get; set; }
        public Nullable<int> AppInfo_ID { get; set; }

        public virtual FiveStarApplicantInformation FiveStarApplicantInformation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FiveStarResidentInformation> FiveStarResidentInformation { get; set; }
    }
}
